#!/bin/bash

# vérifier l'installation de mySQL
# activer le mode debug dans le script 
mPath=$(which mysqld)

if [ $? -eq 1 ]
then 
	apt update
	apt upgrade
        apt install mariadb-server
	echo "la base de données en cours de création"

fi

